ALTER TABLE "Share" ADD COLUMN "showSelfRating" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Share" ADD COLUMN "showDosDonts" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Share" ADD COLUMN "showWeeklyGoals" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Share" ADD COLUMN "showOkrs" BOOLEAN NOT NULL DEFAULT true;
